# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

arch:
  - amd64
  - ppc64le
language: python

matrix:
  include:
  - python: 3.6
    env: TOXENV=py36-aiohttp30
  - python: 3.6
    env: TOXENV=py36-aiohttp31
  - python: 3.6
    env: TOXENV=py36-aiohttp32
  - python: 3.6
    env: TOXENV=py36-aiohttp33
  - python: 3.6
    env: TOXENV=py36-aiohttp34
  - python: 3.6
    env: TOXENV=py36-aiohttp35
  - python: 3.6
    env: TOXENV=py36-aiohttp36
  - python: 3.6
    env: TOXENV=py36-aiohttp37

  - python: 3.7
    dist: xenial
    env: TOXENV=py37-aiohttp33
  - python: 3.7
    dist: xenial
    env: TOXENV=py37-aiohttp34
  - python: 3.7
    dist: xenial
    env: TOXENV=py37-aiohttp35
  - python: 3.7
    dist: xenial
    env: TOXENV=py37-aiohttp36
  - python: 3.7
    dist: xenial
    env: TOXENV=py37-aiohttp37

  - python: 3.8
    dist: xenial
    env: TOXENV=py38-aiohttp33
  - python: 3.8
    dist: xenial
    env: TOXENV=py38-aiohttp34
  - python: 3.8
    dist: xenial
    env: TOXENV=py38-aiohttp35
  - python: 3.8
    dist: xenial
    env: TOXENV=py38-aiohttp36
  - python: 3.8
    dist: xenial
    env: TOXENV=py38-aiohttp37

  - python: 3.9
    dist: focal
    env: TOXENV=py39-aiohttp37
#  - python: 3.8
#    dist: xenial
#    env: TOXENV=py38-aiohttp-master

  - python: 3.8
    dist: xenial
    env: TOXENV=flake8

env:
  global:
    - PYTEST_ADDOPTS="--cov --cov-report=xml"

install: pip install -U tox

after_success:
  - bash <(curl -s https://codecov.io/bash) -Z -X coveragepy -X gcov -X xcode -f coverage.xml

script: tox -e ${TOXENV}
